### ISSUE TITLE
Can't connect to API

### ISSUE THREAD

**Issue by BoB5231** [bkuhl/cryptometer#10]
There is a problem with connection to API >> https://api.coinmarketcap.com/v1/ticker/ <<
Two options in my opinion:
a) switch to the new CoinMarketCap API with free account and pass key per user
b) change the API for different project. Bitstamp for example:
https://www.bitstamp.net/api/ticker/
or
https://www.bitstamp.net/api/v2/ticker/{currency_pair}/
Supported values for currency_pair: btcusd, btceur, eurusd, xrpusd, xrpeur, xrpbtc, ltcusd, ltceur, ltcbtc, ethusd, etheur, ethbtc, bchusd, bcheur, bchbtc

**Comment by BNWEIN** [comment]
Assume this is the same issue i am having.  Is there something i can do to fix it?

**Comment by tmlee** [comment]
Suggest considering the CoinGecko API as an alternative . No keys required and easy to implement, more info can be found at https://www.coingecko.com/en/api

Here is an example endpoint you can use https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false

**Comment by BNWEIN** [comment]
If i put my ini file i dont suppose you could help fix it?

**Comment by BNWEIN** [comment]
`; ------------------------------------------------------------------------
;    _       ___      _______     _       ___     __           __
;   | |     / (_)___ /  / __ \   | |     / (_)___/ /___  ___  / /______
;   | | /| / / / __ \/ / / / /   | | /| / / / __  / __ \/ _ \/ __/ ___/
;   | |/ |/ / / / / / / /_/ /    | |/ |/ / / /_/ / /_/ /  __/ /_(__  ) 
;   |__/|__/_/_/ /_/_/\____/     |__/|__/_/\__,_/\__, /\___/\__/____/
;                                               /____/
;
;	Note: This is not an official  Win10Widgets.com widget, but does depend
;   on Win10 widgets as it inherits the coloring/styles.
;
;	@link http://win10widgets.com
;
; ------------------------------------------------------------------------

[Metadata]
Name=Cryptometer (medium)
Author=Ben Kuhl
Information=Tracks a given set of cryptocurrencies.  For the README, visit https://github.com/bkuhl/cryptometer or from the Rainmeter window, right click the "Cryptometer" directory and choose "Open Folder"
License=Creative Commons BY-NC-SA 4.0
Version=1.0.0

[Variables]
@Include1=#@#variables.ini
@Include2=#@#styles.ini
@Include3=#@#background.ini
BackgroundHeight=210
LeftPadding=10
TopPadding=10
RowHeight=24

# Adjusts the distance columns are from the left of the widget
ColumnValueLeftPadding=(#LeftPadding#+50)
Column1hrLeftPadding=(#LeftPadding#+180)
Column24hrLeftPadding=(#LeftPadding#+240)
Column7dLeftPadding=(#LeftPadding#+300)

[StyleGreenText]
FontColor=0,153,51,255

[StyleRedText]
FontColor=210,72,54,255

# Column Headers__________________________________________________________________
[MeasureBTCUSDValue]
Measure=Plugin
Plugin=WebParser
URL=[MeasureBTC]
StringIndex=1

[MeterColumn1hr]
Meter=String
MeterStyle=StyleSmallText | StyleWhiteText | StyleLeftAlign
X=#Column1hrLeftPadding#
Y=#TopPadding#
Text=1hr

[MeterColumn24hr]
Meter=String
MeterStyle=StyleSmallText | StyleWhiteText | StyleLeftAlign
X=#Column24hrLeftPadding#
Y=#TopPadding#
Text=24hr

[MeterColumn7d]
Meter=String
MeterStyle=StyleSmallText | StyleWhiteText | StyleLeftAlign
X=#Column7dLeftPadding#
Y=#TopPadding#
Text=7d

# Bitcoin (BTC)__________________________________________________________________
[MeasureBTC]
Measure=Plugin
Plugin=WebParser
URL=https://api.coinmarketcap.com/v1/ticker/bitcoin/
RegExp=(?siU)last": "(.*)".*percent_change_1h": "(.*)".*percent_change_24h": "(.*)".*percent_change_7d": "(.*)"
UpdateRate=900 # every 15 minutes

# Extract each column's value by the index
[MeasureBTCUSDValue]
Measure=Plugin
Plugin=WebParser
URL=[MeasureBTC]
StringIndex=1

[MeasureBTC1hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureBTC]
StringIndex=2
IfCondition=MeasureBTC1hr < 0
IfTrueAction=[!SetOption MeterBTCColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterBTCColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureBTC24hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureBTC]
StringIndex=3
IfCondition=MeasureBTC24hr < 0
IfTrueAction=[!SetOption MeterBTCColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterBTCColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureBTC7d]
Measure=Plugin
Plugin=WebParser
URL=[MeasureBTC]
StringIndex=4
IfCondition=MeasureBTC7d < 0
IfTrueAction=[!SetOption MeterBTCColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterBTCColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

# Render the columns with their appropriate values
[MeterBTCColumnLabel]
Meter=String
MeterStyle=StyleSmallText | StyleLeftAlign
X=#LeftPadding#
Y=(#TopPadding#+(#RowHeight#*1))
Text=BTC
LeftMouseUpAction="https://coinmarketcap.com/currencies/bitcoin/"

[MeterBTCColumnValue]
Meter=String
MeasureName=MeasureBTCUSDValue
MeterStyle=StyleSmallText | StyleLeftAlign
X=#ColumnValueLeftPadding#
Y=(#TopPadding#+(#RowHeight#*1))
Text=$%1

[MeterBTCColumn1hr]
Meter=String
MeasureName=MeasureBTC1hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column1hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*1))
Text=%1%

[MeterBTCColumn24hr]
Meter=String
MeasureName=MeasureBTC24hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column24hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*1))
Text=%1%

[MeterBTCColumn7d]
Meter=String
MeasureName=MeasureBTC7d
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column7dLeftPadding#
Y=(#TopPadding#+(#RowHeight#*1))
Text=%1%

# Ethereum (ETH)__________________________________________________________________
[MeasureETH]
Measure=Plugin
Plugin=WebParser
URL=https://api.coinmarketcap.com/v1/ticker/ethereum/
RegExp=(?siU)price_usd": "(.*)".*percent_change_1h": "(.*)".*percent_change_24h": "(.*)".*percent_change_7d": "(.*)"
UpdateRate=900 # every 15 minutes

# Extract each column's value by the index
[MeasureETHUSDValue]
Measure=Plugin
Plugin=WebParser
URL=[MeasureETH]
StringIndex=1

[MeasureETH1hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureETH]
StringIndex=2
IfCondition=MeasureETH1hr < 0
IfTrueAction=[!SetOption MeterETHColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterETHColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureETH24hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureETH]
StringIndex=3
IfCondition=MeasureETH24hr < 0
IfTrueAction=[!SetOption MeterETHColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterETHColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureETH7d]
Measure=Plugin
Plugin=WebParser
URL=[MeasureETH]
StringIndex=4
IfCondition=MeasureETH7d < 0
IfTrueAction=[!SetOption MeterETHColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterETHColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

# Render the columns with their appropriate values
[MeterETHColumnLabel]
Meter=String
MeterStyle=StyleSmallText | StyleLeftAlign
X=#LeftPadding#
Y=(#TopPadding#+(#RowHeight#*2))
Text=ETH
LeftMouseUpAction="https://coinmarketcap.com/currencies/ethereum/"

[MeterETHColumnValue]
Meter=String
MeasureName=MeasureETHUSDValue
MeterStyle=StyleSmallText | StyleLeftAlign
X=#ColumnValueLeftPadding#
Y=(#TopPadding#+(#RowHeight#*2))
Text=$%1

[MeterETHColumn1hr]
Meter=String
MeasureName=MeasureETH1hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column1hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*2))
Text=%1%

[MeterETHColumn24hr]
Meter=String
MeasureName=MeasureETH24hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column24hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*2))
Text=%1%

[MeterETHColumn7d]
Meter=String
MeasureName=MeasureETH7d
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column7dLeftPadding#
Y=(#TopPadding#+(#RowHeight#*2))
Text=%1%

# Siacoin (SC)__________________________________________________________________
[MeasureSC]
Measure=Plugin
Plugin=WebParser
URL=https://api.coinmarketcap.com/v1/ticker/siacoin/
RegExp=(?siU)price_usd": "(.*)".*percent_change_1h": "(.*)".*percent_change_24h": "(.*)".*percent_change_7d": "(.*)"
UpdateRate=900 # every 15 minutes

# Extract each column's value by the index
[MeasureSCUSDValue]
Measure=Plugin
Plugin=WebParser
URL=[MeasureSC]
StringIndex=1

[MeasureSC1hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureSC]
StringIndex=2
IfCondition=MeasureSC1hr < 0
IfTrueAction=[!SetOption MeterSCColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterSCColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureSC24hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureSC]
StringIndex=3
IfCondition=MeasureSC24hr < 0
IfTrueAction=[!SetOption MeterSCColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterSCColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureSC7d]
Measure=Plugin
Plugin=WebParser
URL=[MeasureSC]
StringIndex=4
IfCondition=MeasureSC7d < 0
IfTrueAction=[!SetOption MeterSCColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterSCColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

# Render the columns with their appropriate values
[MeterSCColumnLabel]
Meter=String
MeterStyle=StyleSmallText | StyleLeftAlign
X=#LeftPadding#
Y=(#TopPadding#+(#RowHeight#*3))
Text=SC
LeftMouseUpAction="https://coinmarketcap.com/currencies/siacoin/"

[MeterSCColumnValue]
Meter=String
MeasureName=MeasureSCUSDValue
MeterStyle=StyleSmallText | StyleLeftAlign
X=#ColumnValueLeftPadding#
Y=(#TopPadding#+(#RowHeight#*3))
Text=$%1

[MeterSCColumn1hr]
Meter=String
MeasureName=MeasureSC1hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column1hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*3))
Text=%1%

[MeterSCColumn24hr]
Meter=String
MeasureName=MeasureSC24hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column24hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*3))
Text=%1%

[MeterSCColumn7d]
Meter=String
MeasureName=MeasureSC7d
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column7dLeftPadding#
Y=(#TopPadding#+(#RowHeight#*3))
Text=%1%

# LUXcoin (LUX)__________________________________________________________________
[MeasureLUX]
Measure=Plugin
Plugin=WebParser
URL=https://api.coinmarketcap.com/v1/ticker/luxcoin/
RegExp=(?siU)price_usd": "(.*)".*percent_change_1h": "(.*)".*percent_change_24h": "(.*)".*percent_change_7d": "(.*)"
UpdateRate=900 # every 15 minutes

# Extract each column's value by the index
[MeasureLUXUSDValue]
Measure=Plugin
Plugin=WebParser
URL=[MeasureLUX]
StringIndex=1

[MeasureLUX1hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureLUX]
StringIndex=2
IfCondition=MeasureLUX1hr < 0
IfTrueAction=[!SetOption MeterLUXColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterLUXColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureLUX24hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureLUX]
StringIndex=3
IfCondition=MeasureLUX24hr < 0
IfTrueAction=[!SetOption MeterLUXColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterLUXColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureLUX7d]
Measure=Plugin
Plugin=WebParser
URL=[MeasureLUX]
StringIndex=4
IfCondition=MeasureLUX7d < 0
IfTrueAction=[!SetOption MeterLUXColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterLUXColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

# Render the columns with their appropriate values
[MeterLUXColumnLabel]
Meter=String
MeterStyle=StyleSmallText | StyleLeftAlign
X=#LeftPadding#
Y=(#TopPadding#+(#RowHeight#*4))
Text=LUX
LeftMouseUpAction="https://coinmarketcap.com/currencies/luxcoin/"

[MeterLUXColumnValue]
Meter=String
MeasureName=MeasureLUXUSDValue
MeterStyle=StyleSmallText | StyleLeftAlign
X=#ColumnValueLeftPadding#
Y=(#TopPadding#+(#RowHeight#*4))
Text=$%1

[MeterLUXColumn1hr]
Meter=String
MeasureName=MeasureLUX1hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column1hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*4))
Text=%1%

[MeterLUXColumn24hr]
Meter=String
MeasureName=MeasureLUX24hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column24hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*4))
Text=%1%

[MeterLUXColumn7d]
Meter=String
MeasureName=MeasureLUX7d
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column7dLeftPadding#
Y=(#TopPadding#+(#RowHeight#*4))
Text=%1%

# Bitcoin Cash (BCH)__________________________________________________________________
[MeasureBCH]
Measure=Plugin
Plugin=WebParser
URL=https://api.coinmarketcap.com/v1/ticker/bitcoin-cash/
RegExp=(?siU)price_usd": "(.*)".*percent_change_1h": "(.*)".*percent_change_24h": "(.*)".*percent_change_7d": "(.*)"
UpdateRate=900 # every 15 minutes

# Extract each column's value by the index
[MeasureBCHUSDValue]
Measure=Plugin
Plugin=WebParser
URL=[MeasureBCH]
StringIndex=1

[MeasureBCH1hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureBCH]
StringIndex=2
IfCondition=MeasureBCH1hr < 0
IfTrueAction=[!SetOption MeterBCHColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterBCHColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureBCH24hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureBCH]
StringIndex=3
IfCondition=MeasureBCH24hr < 0
IfTrueAction=[!SetOption MeterBCHColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterBCHColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureBCH7d]
Measure=Plugin
Plugin=WebParser
URL=[MeasureBCH]
StringIndex=4
IfCondition=MeasureBCH7d < 0
IfTrueAction=[!SetOption MeterBCHColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterBCHColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

# Render the columns with their appropriate values
[MeterBCHColumnLabel]
Meter=String
MeterStyle=StyleSmallText | StyleLeftAlign
X=#LeftPadding#
Y=(#TopPadding#+(#RowHeight#*5))
Text=BCH
LeftMouseUpAction="https://coinmarketcap.com/currencies/bitcoin-cash/"

[MeterBCHColumnValue]
Meter=String
MeasureName=MeasureBCHUSDValue
MeterStyle=StyleSmallText | StyleLeftAlign
X=#ColumnValueLeftPadding#
Y=(#TopPadding#+(#RowHeight#*5))
Text=$%1

[MeterBCHColumn1hr]
Meter=String
MeasureName=MeasureBCH1hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column1hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*5))
Text=%1%

[MeterBCHColumn24hr]
Meter=String
MeasureName=MeasureBCH24hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column24hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*5))
Text=%1%

[MeterBCHColumn7d]
Meter=String
MeasureName=MeasureBCH7d
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column7dLeftPadding#
Y=(#TopPadding#+(#RowHeight#*5))
Text=%1%

# Ripple (XRP)__________________________________________________________________
[MeasureXRP]
Measure=Plugin
Plugin=WebParser
URL=https://api.coinmarketcap.com/v1/ticker/ripple/
RegExp=(?siU)price_usd": "(.*)".*percent_change_1h": "(.*)".*percent_change_24h": "(.*)".*percent_change_7d": "(.*)"
UpdateRate=900 # every 15 minutes

# Extract each column's value by the index
[MeasureXRPUSDValue]
Measure=Plugin
Plugin=WebParser
URL=[MeasureXRP]
StringIndex=1

[MeasureXRP1hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureXRP]
StringIndex=2
IfCondition=MeasureXRP1hr < 0
IfTrueAction=[!SetOption MeterXRPColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterXRPColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureXRP24hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureXRP]
StringIndex=3
IfCondition=MeasureXRP24hr < 0
IfTrueAction=[!SetOption MeterXRPColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterXRPColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureXRP7d]
Measure=Plugin
Plugin=WebParser
URL=[MeasureXRP]
StringIndex=4
IfCondition=MeasureXRP7d < 0
IfTrueAction=[!SetOption MeterXRPColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterXRPColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

# Render the columns with their appropriate values
[MeterXRPColumnLabel]
Meter=String
MeterStyle=StyleSmallText | StyleLeftAlign
X=#LeftPadding#
Y=(#TopPadding#+(#RowHeight#*6))
Text=XRP
LeftMouseUpAction="https://coinmarketcap.com/currencies/ripple/"

[MeterXRPColumnValue]
Meter=String
MeasureName=MeasureXRPUSDValue
MeterStyle=StyleSmallText | StyleLeftAlign
X=#ColumnValueLeftPadding#
Y=(#TopPadding#+(#RowHeight#*6))
Text=$%1

[MeterXRPColumn1hr]
Meter=String
MeasureName=MeasureXRP1hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column1hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*6))
Text=%1%

[MeterXRPColumn24hr]
Meter=String
MeasureName=MeasureXRP24hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column24hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*6))
Text=%1%

[MeterXRPColumn7d]
Meter=String
MeasureName=MeasureXRP7d
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column7dLeftPadding#
Y=(#TopPadding#+(#RowHeight#*6))
Text=%1%

# Litecoin (LTC)__________________________________________________________________
[MeasureLTC]
Measure=Plugin
Plugin=WebParser
URL=https://api.coinmarketcap.com/v1/ticker/litecoin/
RegExp=(?siU)price_usd": "(.*)".*percent_change_1h": "(.*)".*percent_change_24h": "(.*)".*percent_change_7d": "(.*)"
UpdateRate=900 # every 15 minutes

# Extract each column's value by the index
[MeasureLTCUSDValue]
Measure=Plugin
Plugin=WebParser
URL=[MeasureLTC]
StringIndex=1

[MeasureLTC1hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureLTC]
StringIndex=2
IfCondition=MeasureLTC1hr < 0
IfTrueAction=[!SetOption MeterLTCColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterLTCColumn1hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureLTC24hr]
Measure=Plugin
Plugin=WebParser
URL=[MeasureLTC]
StringIndex=3
IfCondition=MeasureLTC24hr < 0
IfTrueAction=[!SetOption MeterLTCColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterLTCColumn24hr MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

[MeasureLTC7d]
Measure=Plugin
Plugin=WebParser
URL=[MeasureLTC]
StringIndex=4
IfCondition=MeasureLTC7d < 0
IfTrueAction=[!SetOption MeterLTCColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleRedText"]
IfFalseAction=[!SetOption MeterLTCColumn7d MeterStyle "StyleSmallText | StyleLeftAlign | StyleGreenText"]

# Render the columns with their appropriate values
[MeterLTCColumnLabel]
Meter=String
MeterStyle=StyleSmallText | StyleLeftAlign
X=#LeftPadding#
Y=(#TopPadding#+(#RowHeight#*7))
Text=LTC
LeftMouseUpAction="https://coinmarketcap.com/currencies/litecoin/"

[MeterLTCColumnValue]
Meter=String
MeasureName=MeasureLTCUSDValue
MeterStyle=StyleSmallText | StyleLeftAlign
X=#ColumnValueLeftPadding#
Y=(#TopPadding#+(#RowHeight#*7))
Text=$%1

[MeterLTCColumn1hr]
Meter=String
MeasureName=MeasureLTC1hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column1hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*7))
Text=%1%

[MeterLTCColumn24hr]
Meter=String
MeasureName=MeasureLTC24hr
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column24hrLeftPadding#
Y=(#TopPadding#+(#RowHeight#*7))
Text=%1%

[MeterLTCColumn7d]
Meter=String
MeasureName=MeasureLTC7d
MeterStyle=StyleSmallText | StyleLeftAlign
X=#Column7dLeftPadding#
Y=(#TopPadding#+(#RowHeight#*7))
Text=%1%
`

**Comment by brainstormer3009** [comment]
I did not understood, what's to. Please give the world a tutorial !!!!
Or is the widget dead?

**Comment by bkuhl** [comment]
Personally I no longer use the widget.  I'd gladly merge PRs that solve open issues though.

**Comment by thickconfusion** [comment]
It will take more than a PR, so I'll just tell you what I did to get it working:

If you use a browser to hit the [obsolete V1 API](https://api.coinmarketcap.com/v1/ticker/), you will get a message that reads, "WARNING: This API is now offline. Please switch to the new CoinMarketCap API. (https://pro.coinmarketcap.com/migrate/)".

1. You will need to sign up for your own [free Basic Plan account](https://pro.coinmarketcap.com/signup/?plan=0) with Coin Market Cap.
2. Once you have that token, you will need to edit your skin in the following places:
`URL=https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?symbol=BTC`
Replace **BTC** with the crypto you are interested in.
3. You need to add your API key as a header. Use Rainmeter's header feature to add a line beneath the URL:
`Header=X-CMC_PRO_API_KEY: YOUR-API-CODE-GOES-HERE`

If you get stuck like I did, you can get an API for Coinmarketcap's [free sandbox API](http://sandbox.coinmarketcap.com/) that simply has stale data for test purposes. It's a different URL and you will need a separate API token, but you can try it as many times as you would like without it costing you any quota hits.

**Comment by brainstormer3009** [comment]
Very nice! Thank you!!
But I completely get stuck. No datas shown !

`...er\Cryptometer-Medium.ini - [MeasureBTC]: RegExp matching error (-1)`

```
[MeasureBTC]
Measure=Plugin
Plugin=WebParser
header=X-CMC_PRO_API_KEY: MY API-CODE
URL=https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?symbol=BTC

RegExp=(?siU)price": "(.*)".percent_change_1h": "(.)".percent_change_24h": "(.)".percent_change_7d": "(.)"
UpdateRate=900 # every 15 minutes
```

**Comment by thickconfusion** [comment]
Looks like you have a problem with your RegEx. I adapted mine to this to match what is spit out from the API. Try commenting yours out and using this one (one long line):

`RegExp=(?siU)"price": (\d*\.\d{0,2}?).*percent_change_1h": ([-+]?\d*\.\d{0,2}?).*percent_change_24h": ([-+]?\d*\.\d{0,2}?).*percent_change_7d": ([-+]?\d*\.\d{0,2}?)`

**Comment by bkuhl** [comment]
If that regex fixes the output, can you open a PR for it?  I'd like to keep this as easy-to-use as possible even if there's a few manual steps.

**Comment by thickconfusion** [comment]
> If that regex fixes the output, can you open a PR for it? I'd like to keep this as easy-to-use as possible even if there's a few manual steps.

Hopefully this PR addresses it. First time forking & creating a PR :-)

**Comment by bkuhl** [comment]
To my knowledge @thickconfusion's contribution resolves these issues, so I'll close this out.  Thanks so much for the styling adjustments, API support and instructions!
