### ISSUE TITLE
Unable to load tracker info

### ISSUE THREAD

**Issue by MrM3ph** [bkuhl/cryptometer#14]
Hi, I need some support. I installed the tool and created the API key, I also see on the API dashboards the requests are coming in. 

When I refresh the skin the tickets are not being updated though.

In the error log i get these errors:

DBUG (10:17:14.987) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini: Reading file: C:\Users\xxx\Documents\Rainmeter\Skins\Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini
DBUG (10:17:14.989) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini: Reading file: C:\Users\xxx\Documents\Rainmeter\Skins\Win10 Widgets\@Resources\variables.ini
DBUG (10:17:14.991) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini: Reading file: C:\Users\xxx\Documents\Rainmeter\Skins\Win10 Widgets\@Resources\styles.ini
DBUG (10:17:14.996) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini: Reading file: C:\Users\xxx\Documents\Rainmeter\Skins\Win10 Widgets\@Resources\background.ini
DBUG (10:17:15.018) : ProxyServer="/auto" (type=PRECONFIG, handle=0x0000000000CC0004) UserAgent=Rainmeter WebParser plugin
DBUG (10:17:15.028) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini: !WriteKeyValue: Writing to: C:\Users\Imagine\AppData\Roaming\Rainmeter\Rainmeter.ini
DBUG (10:17:15.032) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini - [MeasureBTC]: Fetching: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?symbol=BTC
DBUG (10:17:15.033) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini - [MeasureBCH]: Fetching: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?symbol=ETH
DBUG (10:17:15.034) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini - [MeasureBCH]: Fetching: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?symbol=BCH
DBUG (10:17:15.035) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini - [MeasureBTC]: Fetching: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?symbol=XRP
DBUG (10:17:15.035) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini - [MeasureBTC]: Fetching: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?symbol=LTC
ERRO (10:17:15.215) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini - [MeasureBTC]: RegExp matching error (-1)
ERRO (10:17:15.241) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini - [MeasureETH]: RegExp matching error (-1)
ERRO (10:17:15.415) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini - [MeasureLTC]: RegExp matching error (-1)
ERRO (10:17:15.575) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini - [MeasureBCH]: RegExp matching error (-1)
ERRO (10:17:15.657) Win10 Widgets\Cryptometer\cryptometer-master\Cryptometer-Medium.ini - [MeasureXRP]: RegExp matching error (-1)

Am I missing something?

**Comment by bkuhl** [comment]
I'm wondering if https://github.com/bkuhl/cryptometer/pull/15 resolves this.  I'll close for now, please re-open if it's still and issue.
