### ISSUE TITLE
Adding currency support other than USD

### ISSUE THREAD

**Issue by markhankins** [bkuhl/cryptometer#6]
I was trying to add a new row in my attempts to add GBP instead of USD (in the hope of adding the option specify in the future into the core config of the plugin). 

I have the additional row added no problem, and from the API docs, I know this returns the GBP value, but the regex does not work for some reason?  (Sorry, I'm terrible with regex, but I thought it would work?)

https://api.coinmarketcap.com/v1/ticker/ethereum/?convert=GBP - Returns the gbp value, so I thought updating the regex to capture the following should work?

RegExp=(?siU)price_gbp": "(.*)".*percent_change_1h": "(.*)".*percent_change_24h": "(.*)".*percent_change_7d": "(.*)"

I get nothing returned?  Any idea why?  If I can sort this, I'll issue a PR and if you like it, can merge it.

**Comment by Beguiled** [comment]
A few changes need to be made that I can see (and this is a work in progress)

The RegExp should read something like this:
`RegExp=(?siU)price_usd": "(.*)".*percent_change_1h": "(.*)".*percent_change_24h": "(.*)".*percent_change_7d": "(.*)".*price_gbp": "(.*)"`

`price_gbp` comes after the other values in the JSON return data and needs to be captured as such. This would need to be considered for any other conversions as well.

`MeasureETHUSDValue` would need to have it's `StringIndex` value updated to represent the new column location:
`StringIndex=5`

It may also be argued that the title would change to **MeasureETHValue** instead.

If you give that a try you should see better results. However, I'm seeing a very long decimal value for GBP right now that runs over the column width and into the 1hr column. This would need to be addressed with additional formatting.

**Comment by markhankins** [comment]
I got it all working, except the chopping down to 2dp.  I had a go, but no idea how to do that...

I switched to "MeasureETHGBPValue"
