### ISSUE TITLE
Coinmarketcap Values Are Too Many Digits & Overlap

### ISSUE THREAD

**Issue by thickconfusion** [bkuhl/cryptometer#9]
https://github.com/bkuhl/cryptometer/blob/e4a7b6535439a8cb059a5923c55c39bc6f5c944c/Cryptometer-Medium.ini#L78

I cloned this repository and began using this great tool. Unforunately, Coinmarketcap's API is now producing several decimal digits of precision on prices and overlapping into the next column. Consider limiting the number of digits for example:

`RegExp=(?siU)price_usd": "(\d*\.\d{0,4}?).*percent_change_1h": "(.*)".*percent_change_24h": "(.*)".*percent_change_7d": "(.*)"`

**Comment by Crsmsg** [comment]
any fix ?

**Comment by bkuhl** [comment]
Sorry about the lack of response on this repo.  If you have a fix, I'd gladly merge it in.

**Comment by bkuhl** [comment]
^ Should have resolved this
